import json
import re
import csv
import os
import torch
from json_repair import repair_json

# ─── Prompt ───────────────────────────────────────────────────────────────────

OPTIMIZATION_PROMPT_TEMPLATE = """
You are Agent 4, a Sustainability-Oriented Metamorphic Test Optimization Agent.

Your job is to prioritize and optimize the metamorphic relations generated by Agent 3.
The goal is to reduce redundant executions while preserving important behavioral coverage.

---

## INPUT
Screen ID: {screen_id}
Topic: {topic}

METAMORPHIC RELATIONS FROM AGENT 3 (columns separated by ::):
{mr_csv}

---

## OPTIMIZATION CRITERIA (apply all 6)

1. BEHAVIORAL IMPORTANCE
   Core app behavior MRs must be kept.
   Keep: MONOTONICITY, INVARIANCE, VALIDATION CONSISTENCY relations.

2. FAULT DETECTION POTENTIAL
   MRs that can reveal real defects get high priority.
   High priority: boundary transitions, invalid-to-valid, unit conversion.

3. REDUNDANCY / OVERLAP
   ROBUSTNESS MRs: if multiple ROBUSTNESS MRs exist, keep the first one as "keep" and
   mark the rest as "reduce_repetitions" or "partial_sampling".
   VALIDATION_CONSISTENCY MRs: each one tests a DIFFERENT input field (age, waist, height
   are all separate fields). They are NEVER redundant with each other — always keep all of them.
   Never mark VALIDATION_CONSISTENCY as lower_priority unless it is literally identical
   in both transformation AND field to another MR in the same list.

4. EXECUTION DIVERSITY
   Keep at least one MR from each category that appears in the input.
   Do partial sampling rather than full removal.

5. REPRESENTATIVE COVERAGE
   Ensure at least one MR from EVERY category that appears in the input survives.
   The FIRST MR of each category must always be "keep" or "high_priority_keep" — never
   "reduce_repetitions" or "partial_sampling". Only subsequent MRs of the same category
   on the same element can be downgraded.

6. EXECUTION COST
   Mark repeated low-value interactions as "lower_frequency" instead of deleting them.

---

## DECISION VALUES (use exactly these strings)
- "keep"                → important, run every time
- "high_priority_keep"  → critical, always run first
- "lower_priority"      → domain-dependent or weak, run but deprioritize
- "reduce_repetitions"  → overlaps another MR, reduce how often run
- "partial_sampling"    → keep but only sample occasionally

---

## RULES
- Do NOT aggressively delete MRs — prefer downgrading to removing.
- Every mr_id from input must appear in output with a decision.
- Reason must be a short, specific sentence (not generic).
- If only 1 MR exists for a category, never remove it entirely.

---

## OUTPUT
Return ONLY valid JSON, no markdown, no explanation.

{{
  "screen_id": "{screen_id}",
  "optimized_relations": [
    {{
      "mr_id": "MR-01",
      "source_tc_id": "TC_{screen_id}_001",
      "mr_category": "MONOTONICITY",
      "transformation": "...",
      "expected_relation": "...",
      "decision": "high_priority_keep",
      "reason": "Core mathematical behavior — waist increase must raise ratio"
    }}
  ]
}}
"""

# ─── CSV columns ──────────────────────────────────────────────────────────────

OPT_CSV_COLUMNS = [
    "mr_id",
    "source_tc_id",
    "screen_id",
    "topic",
    "mr_category",
    "transformation",
    "expected_relation",
    "decision",
    "reason",
]

# Maps decision value → numeric priority for sorting final output
DECISION_ORDER = {
    "high_priority_keep":  1,
    "keep":                2,
    "partial_sampling":    3,
    "reduce_repetitions":  4,
    "lower_priority":      5,
}


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _mr_data_to_csv_string(mr_data: dict) -> str:
    """Convert Agent 3 MR dict to a compact CSV string for the prompt."""
    lines = ["mr_id :: source_tc_id :: mr_category :: transformation :: expected_relation :: confidence"]
    for mr in mr_data.get("metamorphic_relations", []):
        lines.append(
            f"{mr.get('mr_id','')} :: {mr.get('source_tc_id','')} :: "
            f"{mr.get('mr_category','')} :: {mr.get('transformation','')} :: "
            f"{mr.get('expected_relation','')} :: {mr.get('confidence','')}"
        )
    return "\n".join(lines)


def _build_mr_lookup(mr_data: dict) -> dict:
    """Build a dict of mr_id → full MR record for enriching Agent 4 output."""
    return {
        mr.get("mr_id", ""): mr
        for mr in mr_data.get("metamorphic_relations", [])
    }


def _safe_join(val):
    if not val:
        return ""
    if isinstance(val, str):
        return val
    return ", ".join(
        str(v) if not isinstance(v, dict) else json.dumps(v)
        for v in val
    )


def _sort_by_decision(optimized: list) -> list:
    """Sort optimized MRs by decision priority (high_priority_keep first)."""
    return sorted(
        optimized,
        key=lambda x: DECISION_ORDER.get(x.get("decision", "lower_priority"), 99),
    )


# ─── Main optimization function ───────────────────────────────────────────────

def optimize_metamorphic_relations(mr_data: dict, model, tokenizer) -> dict:
    """
    Agent 4: takes Agent 3 MR output and returns prioritized/optimized MRs.
    Uses the same Qwen 2.5-7B model as Agents 2 and 3.
    """
    screen_id = mr_data.get("screen_id", "unknown")
    topic     = mr_data.get("topic", "unknown")

    if not mr_data.get("metamorphic_relations"):
        print("   ⚠️  Agent 4: No MRs to optimize — skipping")
        return {"screen_id": screen_id, "topic": topic, "optimized_relations": []}

    mr_csv     = _mr_data_to_csv_string(mr_data)
    mr_lookup  = _build_mr_lookup(mr_data)

    prompt = OPTIMIZATION_PROMPT_TEMPLATE.format(
        screen_id=screen_id,
        topic=topic,
        mr_csv=mr_csv,
    )

    messages = [
        {
            "role": "system",
            "content": (
                "You are a test suite optimization expert. "
                "Output ONLY valid JSON with no markdown or explanation."
            ),
        },
        {"role": "user", "content": prompt},
    ]

    text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=4096,
    ).to("cuda")

    print(f"   🔄 Optimizing metamorphic relations (Agent 4)...")

    with torch.no_grad():
        ids = model.generate(
            **inputs,
            max_new_tokens=2000,
            do_sample=False,
            top_p=1.0,
            repetition_penalty=1.05,
            pad_token_id=tokenizer.eos_token_id,
        )

    raw = tokenizer.decode(
        ids[0][inputs.input_ids.shape[1]:], skip_special_tokens=True
    )

    try:
        blocks = re.findall(r"\{.*\}", raw, re.DOTALL)
        if not blocks:
            print("   ⚠️  Agent 4: No JSON block found — returning all MRs as 'keep'")
            return _fallback_keep_all(mr_data)

        candidate = max(blocks, key=len)
        repaired  = repair_json(candidate)
        result    = json.loads(repaired)

        optimized = result.get("optimized_relations", [])

        # Enrich with any missing fields from Agent 3 lookup
        for opt in optimized:
            mr_id = opt.get("mr_id", "")
            if mr_id in mr_lookup:
                src = mr_lookup[mr_id]
                opt.setdefault("source_tc_id",   src.get("source_tc_id", ""))
                opt.setdefault("mr_category",     src.get("mr_category", ""))
                opt.setdefault("transformation",  src.get("transformation", ""))
                opt.setdefault("expected_relation", src.get("expected_relation", ""))

        # Validate decision values — fix anything unexpected
        valid_decisions = set(DECISION_ORDER.keys())
        for opt in optimized:
            if opt.get("decision") not in valid_decisions:
                opt["decision"] = "keep"

        optimized = _sort_by_decision(optimized)
        optimized = _enforce_coverage_rules(optimized, mr_data)

        result["optimized_relations"] = optimized
        result["screen_id"] = screen_id
        result["topic"]     = topic

        print(f"   ✅ Agent 4 optimized {len(optimized)} MRs")
        _print_summary(optimized)
        return result

    except Exception as e:
        print(f"   ❌ Agent 4 JSON parse failed: {e} — returning fallback")
        return _fallback_keep_all(mr_data)



def _enforce_coverage_rules(optimized: list, mr_data: dict) -> list:
    """
    Post-processing safety net that enforces hard rules regardless of model output.

    1. Exactly ONE MR per category survives as the "first instance" baseline —
       every later MR in the same category that Qwen also marked keep/high_priority_keep
       gets capped to reduce_repetitions. (Fixes bug: Sync.me previously had three
       separate ROBUSTNESS MRs each kept with "first instance" reasoning, one per icon.)

    2. EXCEPTION: categories in NEVER_REDUNDANT_CATEGORIES (VALIDATION_CONSISTENCY,
       INVARIANCE) get the survivor slot applied PER source_tc_id, not once per
       category — because different fields (age/waist/height) or different elements
       (THIS COURSE tab/TOTAL tab) are never true duplicates of each other even
       though they share a category label.

    3. Whenever this function changes a decision, OR finds a decision whose existing
       reason text contradicts it (e.g. decision="keep" but reason says "reduce
       repetitions"), the reason is fully replaced rather than appended to. (Fixes
       bug: Screen 295's MR-02 had decision="keep" with a leftover reason from before
       the coverage rule overrode it, so the two disagreed.)
    """
    mr_lookup = {mr.get("mr_id", ""): mr for mr in mr_data.get("metamorphic_relations", [])}

    NEVER_REDUNDANT_CATEGORIES = {"VALIDATION_CONSISTENCY", "INVARIANCE"}

    _DEMOTION_LANGUAGE = ("reduce repetition", "redundant", "lower priority", "lower_priority")

    def _sanitize_contradictory_reason(opt: dict, fallback: str) -> None:
        """If decision is keep/high_priority_keep but reason text argues the
        opposite, replace the reason. Safe to call even when nothing changed."""
        reason = (opt.get("reason") or "").lower()
        decision = opt.get("decision", "")
        if decision in ("keep", "high_priority_keep") and any(p in reason for p in _DEMOTION_LANGUAGE):
            opt["reason"] = fallback

    # ── Rule 1: one survivor per category, except NEVER_REDUNDANT_CATEGORIES
    seen_categories = set()
    for opt in optimized:
        cat = opt.get("mr_category", "")
        decision = opt.get("decision", "")

        if cat in NEVER_REDUNDANT_CATEGORIES:
            continue  # handled per-source_tc_id in Rule 1b below

        if cat not in seen_categories:
            seen_categories.add(cat)
            if decision in ("reduce_repetitions", "partial_sampling", "lower_priority"):
                opt["decision"] = "keep"
                opt["reason"] = "Coverage rule: first MR of category must survive"
            else:
                _sanitize_contradictory_reason(
                    opt, "Coverage rule: first MR of category must survive"
                )
            continue

        if decision in ("keep", "high_priority_keep"):
            opt["decision"] = "reduce_repetitions"
            opt["reason"] = (
                f"Coverage rule: only the first {cat} MR per screen is kept as "
                f"the baseline; this is a repeat of the same category"
            )

    # ── Rule 1b: NEVER_REDUNDANT_CATEGORIES get one survivor PER source_tc_id,
    # not one per category — different fields/elements are never duplicates.
    seen_per_category_tc: set[tuple] = set()
    for opt in optimized:
        cat = opt.get("mr_category", "")
        if cat not in NEVER_REDUNDANT_CATEGORIES:
            continue

        key = (cat, opt.get("source_tc_id", ""))
        decision = opt.get("decision", "")

        if key not in seen_per_category_tc:
            seen_per_category_tc.add(key)
            if decision in ("reduce_repetitions", "partial_sampling", "lower_priority"):
                opt["decision"] = "keep"
                opt["reason"] = f"{cat} on a distinct source test case — never redundant, must be kept"
            else:
                _sanitize_contradictory_reason(
                    opt, f"{cat} on a distinct source test case — never redundant, must be kept"
                )
        else:
            # True duplicate: same category AND same source_tc_id seen before.
            if decision in ("keep", "high_priority_keep"):
                opt["decision"] = "reduce_repetitions"
                opt["reason"] = (
                    f"Coverage rule: duplicate {cat} MR on the same source test case"
                )

    return optimized

def _fallback_keep_all(mr_data: dict) -> dict:
    """If Agent 4 fails to parse, keep all MRs with decision='keep'."""
    screen_id = mr_data.get("screen_id", "unknown")
    topic     = mr_data.get("topic", "unknown")
    optimized = []
    for mr in mr_data.get("metamorphic_relations", []):
        optimized.append({
            "mr_id":             mr.get("mr_id", ""),
            "source_tc_id":      mr.get("source_tc_id", ""),
            "mr_category":       mr.get("mr_category", ""),
            "transformation":    mr.get("transformation", ""),
            "expected_relation": mr.get("expected_relation", ""),
            "decision":          "keep",
            "reason":            "Fallback — Agent 4 parse failed",
        })
    return {"screen_id": screen_id, "topic": topic, "optimized_relations": optimized}


def _print_summary(optimized: list):
    """Print a compact decision summary to console."""
    from collections import Counter
    counts = Counter(opt.get("decision", "") for opt in optimized)
    summary = " | ".join(f"{d}: {n}" for d, n in sorted(counts.items()))
    print(f"   📊 Decision summary — {summary}")


# ─── Save functions ───────────────────────────────────────────────────────────

def save_optimized_mr_data(
    opt_data: dict,
    out_dir: str = "outputs/optimized_relations",
):
    """Save optimized MRs to individual CSV per screen (e.g. 124_Prioritize_MR.csv)."""
    os.makedirs(out_dir, exist_ok=True)
    screen_id = opt_data.get("screen_id", "unknown")
    topic     = opt_data.get("topic", "unknown")
    optimized = opt_data.get("optimized_relations", [])

    out_path = os.path.join(out_dir, f"{screen_id}_Prioritize_MR.csv")
    if os.path.exists(out_path):
        os.remove(out_path)

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=OPT_CSV_COLUMNS)
        w.writeheader()
        for opt in optimized:
            w.writerow({
                "mr_id":             opt.get("mr_id", ""),
                "source_tc_id":      opt.get("source_tc_id", ""),
                "screen_id":         screen_id,
                "topic":             topic,
                "mr_category":       opt.get("mr_category", ""),
                "transformation":    opt.get("transformation", ""),
                "expected_relation": opt.get("expected_relation", ""),
                "decision":          opt.get("decision", ""),
                "reason":            opt.get("reason", ""),
            })

    print(f"  💾 Optimized MRs saved → {out_path}")
    return out_path


def append_optimized_mr_to_master(
    opt_data: dict,
    master_path: str = "outputs/optimized_relations_master.csv",
):
    """Append optimized MRs to master CSV."""
    os.makedirs(os.path.dirname(master_path), exist_ok=True)
    screen_id = opt_data.get("screen_id", "unknown")
    topic     = opt_data.get("topic", "unknown")
    optimized = opt_data.get("optimized_relations", [])

    exists = os.path.exists(master_path)
    with open(master_path, "a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=OPT_CSV_COLUMNS)
        if not exists:
            w.writeheader()
        for opt in optimized:
            w.writerow({
                "mr_id":             opt.get("mr_id", ""),
                "source_tc_id":      opt.get("source_tc_id", ""),
                "screen_id":         screen_id,
                "topic":             topic,
                "mr_category":       opt.get("mr_category", ""),
                "transformation":    opt.get("transformation", ""),
                "expected_relation": opt.get("expected_relation", ""),
                "decision":          opt.get("decision", ""),
                "reason":            opt.get("reason", ""),
            })

    print(f"  💾 Optimized MRs appended to master → {master_path}")